version: "3.1"
services:

    webserver:
      image: nginx:alpine
      env_file:
        - .env
      container_name: '${CONTAINER_SUFFIX}-webserver'
      working_dir: /application
      volumes:
        - ./public:/application/public
        - ./private:/application/private
        - ./server-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      environment:
        - "VIRTUAL_HOST=${SERVER_VIRTUAL_HOST}" # docker-gen / nginx-proxy
      expose:
        - 80

    php-fpm:
      image: kenorfr/docker-php71
      depends_on:
        - webserver
      env_file:
        - .env
      container_name: '${CONTAINER_SUFFIX}-php-fpm'
      working_dir: /application
      volumes:
        - ./public:/application/public
        - ./private:/application/private
        - ./server-conf/php.ini:/usr/local/etc/php/conf.d/docker-php.ini

    mariadb:
      image: mariadb:10.1
      env_file:
        - .env
      container_name: '${CONTAINER_SUFFIX}-mariadb'
      working_dir: /application
      volumes:
        - ./server-conf/mariadb:/var/lib/mysql
      environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      ports:
        - "${MYSQL_PORT}:3306"

#    redis:
#      image: redis:alpine
#      env_file:
#         - .env
#      container_name: '${CONTAINER_SUFFIX}-redis'
#
#    mailhog:
#      image: mailhog/mailhog:latest
#      env_file:
#         - .env
#      container_name: '${CONTAINER_SUFFIX}-mailhog'
#      ports:
#        - "8112:8025"
#
#    elasticsearch:
#      image: elasticsearch:5.4-alpine
#      env_file:
#         - .env
#      container_name: '${CONTAINER_SUFFIX}-elasticsearch'

# use with webproxy (docker-gen)
networks:
  default:
     external:
       name: webproxy