version: "3.1"
services:

    webserver:
      image: nginx:alpine
      env_file:
        - .env
      container_name: '${CONTAINER_SUFFIX}-webserver'
      working_dir: /application
      volumes:
        - ./public:/application/public
        - ./private:/application/private
        - ./server-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8111:80"

    php-fpm:
      build: kenorfr/php71-fpm
      env_file:
        - .env
      container_name: '${CONTAINER_SUFFIX}-php-fpm'
      working_dir: /application
      volumes:
        - ./public:/application/public
        - ./private:/application/private
        - ./server-conf/php.ini:/usr/local/etc/php/conf.d/docker-php.ini

    mariadb:
      image: mariadb:10.1
      env_file:
        - .env
      container_name: '${CONTAINER_SUFFIX}-mariadb'
      working_dir: /application
      volumes:
        # tous les fichiers de la BDD (permet de sauvegarder si on doit tout reconstruire)
        - ./server-conf/mariadb:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=project_eolook
        - MYSQL_USER=eolook
        - MYSQL_PASSWORD=eolook_pass
      #ports:
      #  - "8114:3306"

#    redis:
#      image: redis:alpine
#      env_file:
#         - .env
#      container_name: '${CONTAINER_SUFFIX}-redis'
#
#    mailhog:
#      image: mailhog/mailhog:latest
#      env_file:
#         - .env
#      container_name: '${CONTAINER_SUFFIX}-mailhog'
#      ports:
#        - "8112:8025"
#
#    elasticsearch:
#      image: elasticsearch:5.4-alpine
#      env_file:
#         - .env
#      container_name: '${CONTAINER_SUFFIX}-elasticsearch'
